export const TOPIC_GET_ALL = 'TOPIC_GET_ALL';
export const TOPIC_GET_ALL_FAIL = 'TOPIC_GET_ALL_FAIL';
export const TOPIC_GET_ALL_SUCCESS = 'TOPIC_GET_ALL_SUCCESS';
export const TOPIC_CREATE = 'TOPIC_CREATE';
export const TOPIC_CREATE_FAIL = 'TOPIC_CREATE_FAIL';
export const TOPIC_CREATE_SUCCESS = 'TOPIC_CREATE_SUCCESS';