//TOPICS
export const TOPIC_GET_ALL = 'TOPIC_GET_ALL';
export const TOPIC_GET_ALL_FAIL = 'TOPIC_GET_ALL_FAIL';
export const TOPIC_GET_ALL_SUCCESS = 'TOPIC_GET_ALL_SUCCESS';
export const TOPIC_CREATE = 'TOPIC_CREATE';
export const TOPIC_CREATE_FAIL = 'TOPIC_CREATE_FAIL';
export const TOPIC_CREATE_SUCCESS = 'TOPIC_CREATE_SUCCESS';
export const TOPIC_UPDATE = 'TOPIC_UPDATE';
export const TOPIC_UPDATE_FAIL = 'TOPIC_UPDATE_FAIL';
export const TOPIC_UPDATE_SUCCESS = 'TOPIC_UPDATE_SUCCESS';
export const TOPIC_REMOVE = 'TOPIC_REMOVE';
export const TOPIC_REMOVE_FAIL = 'TOPIC_REMOVE_FAIL';
export const TOPIC_REMOVE_SUCCESS = 'TOPIC_REMOVE_SUCCESS';

//SOCKETS
export const SOCKET_OPEN = 'SOCKET_OPEN';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
export const SOCKET_CLOSE = 'SOCKET_CLOSE';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
export const SOCKET_CONNECT_FAIL = 'SOCKET_CONNECT_FAIL';
export const SOCKET_SUSBRIBE = 'SOCKET_SUSBRIBE';
export const SOCKET_MESSAGE_FAIL = 'SOCKET_MESSAGE_FAIL';
export const SOCKET_MESSAGE_GREETINGS = 'SOCKET_MESSAGE_GREETINGS';